package com.mpaauw.tome;

public class Colors {

    private final Tome tome;

    protected Colors(Tome tome) {
        this.tome = tome;
    }

    public String common() {
        return commonColors[ContentSeed.getRandomIndex(commonColors.length)];
    }

    private final String[] commonColors = new String[]{
            "amaranth",
            "amber",
            "amethyst",
            "apricot",
            "aquamarine",
            "azure",
            "baby blue",
            "beige",
            "black",
            "blue",
            "blue-green",
            "blue-violet",
            "blush",
            "bronze",
            "brown",
            "burgundy",
            "byzantium",
            "carmine",
            "cerise",
            "cerulean",
            "champagne",
            "chartreuse-green",
            "chocolate",
            "cobalt-blue",
            "coffee",
            "copper",
            "coral",
            "crimson",
            "cyan",
            "desert-sand",
            "electric-blue",
            "emerald",
            "erin",
            "gold",
            "gray",
            "green",
            "harlequin",
            "indigo",
            "ivory",
            "jade",
            "jungle-green",
            "lavender",
            "lemon",
            "lilac",
            "lime",
            "magenta",
            "magenta-rose",
            "maroon",
            "mauve",
            "navy-blue",
            "ochre",
            "olive",
            "orange",
            "orange-red",
            "orchid",
            "peach",
            "pear",
            "periwinkle",
            "persian-blue",
            "pink",
            "plum",
            "prussian-blue",
            "puce",
            "purple",
            "raspberry",
            "red",
            "red-violet",
            "rose",
            "ruby",
            "salmon",
            "sangria",
            "sapphire",
            "scarlet",
            "silver",
            "slate-gray",
            "spring-bud",
            "spring-green",
            "tan",
            "taupe",
            "teal",
            "turquoise",
            "ultramarine",
            "violet",
            "viridian",
            "white",
            "yellow"};
}
